def drawsquare():
    import turtle
    turtle.showturtle()
    thenumber = turtle.numinput('','Enter side length: ')
    thenuber = int(thenumber)
    turtle.forward(thenumber)
    turtle.left(90)
    turtle.forward(thenumber)
    turtle.left(90)
    turtle.forward(thenumber)
    turtle.left(90)
    turtle.forward(thenumber)
    turtle.left(90)

    thenumber = 100
    turtle.left(30)
    turtle.forward(thenumber)
    turtle.left(90)
    turtle.forward(thenumber)
    turtle.left(90)
    turtle.forward(thenumber)
    turtle.left(90)
    turtle.forward(thenumber)
    turtle.left(90)

    thenumber = 200
    turtle.left(30)
    turtle.forward(thenumber)
    turtle.left(90)
    turtle.forward(thenumber)
    turtle.left(90)
    turtle.forward(thenumber)
    turtle.left(90)
    turtle.forward(thenumber)
    turtle.left(90)

    thenumber = 300
    turtle.left(30)
    turtle.forward(thenumber)
    turtle.left(90)
    turtle.forward(thenumber)
    turtle.left(90)
    turtle.forward(thenumber)
    turtle.left(90)
    turtle.forward(thenumber)
    turtle.left(90)
